### ISSUE TITLE
Wired-tabs are not working as of the latest release

### ISSUE THREAD

**Issue by edyu** [rough-stuff/wired-elements#146]
I first tried with some nested elements so I thought maybe that's the problem but even when I use the exact same example index.html for wired-tabs, I'm seeing the same problem. 
![tab_problem](https://user-images.githubusercontent.com/64173/81900389-8d23d400-9571-11ea-869f-278e993e08e4.png)

**Comment by edyu** [comment]
Note that I also tried out other elements such as wired-label, wired-button, wired-search-input etc and they all work fine.

**Comment by apennamen** [comment]
Hello,
I was able to reproduce the issue and this is a weeeeeeird one...
The source code that is printed in the page is the one of the "repeat" directive (wired-tabs is the only component that uses it, that's why you won't have the issue with the others).

Apparently it doesn't append after a build phase, for example with rollup (I have to confirm that). 
No idea where it comes from...

**Comment by pshihn** [comment]
v2.1.1 does not rely on `repeat` any more. 
Try it now. 

If you could link to a reproducible sample it would be great. 
Also sorry for the late response

**Comment by pshihn** [comment]
Working in latest. https://codesandbox.io/s/keen-clarke-ge7zk?file=/index.html
